sudo: false

language: python

python:
  - 3.6

notifications:
  email: false

env:
  global:
    - secure: "Eq7T9I/6s+z9ESn2XXvMK25VdjR3URXZw/rPh4gF1OfDu3cbXbSzXgbv28A0SHh6OQUQeK6MMFUo+EhJXmDK3Waw3f0e1DAHFN99SgRMld8Atv/7/xUDfiobYjC3XMLlX4kJHL1I/mcDm960mzwKOCu/O3sc1ql/AyNsuFRCqoU="
    - secure: "cHX6Q2iRE01i7w27ZdnMPXHpTsKSAD2hiIE1CR7vaMlZWwdryAmT0TG3/fncOikSVzEAcO22u92pXPnBEfsyFP3U4HsMdjF6ooFktzj6o9Mf3iKmwRgXhex3fgqA6mHamNMMkNGYu9VuvYMry7H61qONu6DJREKf30oSvNQCay4="

branches:
  only:
    - master
    - develop

# command to install dependencies
install:
  - pip install --upgrade pip setuptools
  - pip install coverage coveralls twine wheel
  - pip install -r requirements.txt
  - python setup.py install

# command to run tests
script: nosetests --with-coverage --cover-package=pybea

# command to run coveralls
after_success:
  - coveralls
  - scripts/publish.sh
