language: python
python:
  - "2.7"
  - "3.3"

notifications:
  email: false

branches:
  only:
    - master

# command to install dependencies
install:
  - "pip install coverage"
  - "pip install numpy pandas requests"

# command to run tests
script: nosetests --with-coverage --cover-package=pybea

# command to run coveralls
after_success:
  - coveralls