sudo: false

language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

notifications:
  email: false

branches:
  only:
    - master
    - develop

# command to install dependencies
install:
  - pip install coverage coveralls
  - pip install numpy pandas requests
  - python setup.py install

# command to run tests
script: nosetests --with-coverage --cover-package=pybea

# command to run coveralls
after_success:
  - coveralls